import {
  SiAmazonwebservices,
  SiAngular,
  SiCss3,
  SiDocker,
  SiFirebase,
  SiGooglecloud,
  SiGithub,
  SiHtml5,
  SiJavascript,
  SiJenkins,
  SiMysql,
  SiMongodb,
  SiOracle,
  SiPostgresql,
  SiReact,
  SiRubyonrails,
  SiSplunk,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiSpringboot,
} from "react-icons/si";
import { FaJava } from "react-icons/fa";
import type { Skill } from "../../types/skill.types";

export const skills: Skill[] = [
  {
    id: "aws",
    name: "AWS",
    icon: SiAmazonwebservices,
    href: "https://aws.amazon.com/",
    category: "cloud",
    keywords: ["amazon", "cloud", "ec2", "s3", "lambda", "infrastructure"],
    color: "#FF9900",
  },
  {
    id: "angular",
    name: "Angular 17+",
    icon: SiAngular,
    href: "https://angular.dev/",
    category: "frontend",
    keywords: [
      "typescript",
      "google",
      "framework",
      "spa",
      "single page application",
      "components",
      "directives",
      "services",
      "dependency injection",
      "rxjs",
      "observables",
      "reactive",
      "signals",
      "standalone components",
      "control flow",
      "deferrable views",
      "ssr",
      "server side rendering",
      "hydration",
      "angular cli",
      "ng",
      "modules",
      "routing",
      "forms",
      "reactive forms",
      "template driven forms",
      "pipes",
      "guards",
      "interceptors",
      "zoneless",
      "ivy",
      "esbuild",
      "vite",
    ],
    color: "#DD0031",
  },
  {
    id: "css3",
    name: "CSS3",
    icon: SiCss3,
    href: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    category: "frontend",
    keywords: ["styles", "styling", "web", "design"],
    color: "#1572B6",
  },
  {
    id: "docker",
    name: "Docker",
    icon: SiDocker,
    href: "https://www.docker.com/",
    category: "devops",
    keywords: ["container", "kubernetes", "deploy", "containerization"],
    color: "#2496ED",
  },
  {
    id: "firebase",
    name: "Firebase",
    icon: SiFirebase,
    href: "https://firebase.google.com",
    category: "cloud",
    keywords: ["google", "baas", "realtime", "auth", "database"],
    color: "#FFCA28",
  },
  {
    id: "gcp",
    name: "Google Cloud",
    icon: SiGooglecloud,
    href: "https://cloud.google.com",
    category: "cloud",
    keywords: ["google", "cloud", "gcp", "infrastructure"],
    color: "#4285F4",
  },
  {
    id: "github",
    name: "GitHub",
    icon: SiGithub,
    href: "https://www.github.com",
    category: "tools",
    keywords: ["git", "version control", "repository", "code"],
    color: "#FFFFFF",
  },
  {
    id: "html5",
    name: "HTML5",
    icon: SiHtml5,
    href: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    category: "frontend",
    keywords: ["markup", "web", "semantic", "structure"],
    color: "#E34F26",
  },
  {
    id: "java",
    name: "Java",
    icon: FaJava,
    href: "https://www.java.com/en/",
    category: "language",
    keywords: ["jvm", "spring", "enterprise", "backend"],
    color: "#007396",
  },
  {
    id: "javascript",
    name: "JavaScript",
    icon: SiJavascript,
    href: "https://www.javascript.com",
    category: "language",
    keywords: ["js", "ecmascript", "web", "frontend", "node"],
    color: "#F7DF1E",
  },
  {
    id: "jenkins",
    name: "Jenkins",
    icon: SiJenkins,
    href: "https://www.jenkins.io/",
    category: "devops",
    keywords: ["ci", "cd", "pipeline", "automation", "build"],
    color: "#D24939",
  },
  {
    id: "mysql",
    name: "MySQL",
    icon: SiMysql,
    href: "https://www.mysql.com/",
    category: "database",
    keywords: ["sql", "relational", "oracle", "database"],
    color: "#4479A1",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    icon: SiMongodb,
    href: "https://mongodb.com",
    category: "database",
    keywords: ["nosql", "document", "atlas", "database"],
    color: "#47A248",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    icon: SiPostgresql,
    href: "https://www.postgresql.org/",
    category: "database",
    keywords: ["sql", "relational", "postgres", "database"],
    color: "#4169E1",
  },
  {
    id: "react",
    name: "React",
    icon: SiReact,
    href: "https://reactjs.org",
    category: "frontend",
    keywords: ["jsx", "hooks", "components", "ui", "library"],
    color: "#61DAFB",
  },
  {
    id: "rails",
    name: "Ruby on Rails",
    icon: SiRubyonrails,
    href: "https://rubyonrails.org/",
    category: "backend",
    keywords: ["ruby", "mvc", "api", "web", "framework"],
    color: "#CC0000",
  },
  {
    id: "splunk",
    name: "Splunk",
    icon: SiSplunk,
    href: "https://www.splunk.com/",
    category: "devops",
    keywords: ["logging", "monitoring", "observability", "analytics"],
    color: "#000000",
  },
  {
    id: "tailwindcss",
    name: "Tailwind CSS",
    icon: SiTailwindcss,
    href: "https://tailwindcss.com/",
    category: "frontend",
    keywords: ["css", "utility", "design", "styling"],
    color: "#06B6D4",
  },
  {
    id: "typescript",
    name: "TypeScript",
    icon: SiTypescript,
    href: "https://www.typescriptlang.org/",
    category: "language",
    keywords: ["javascript", "types", "static", "ts", "microsoft"],
    color: "#3178C6",
  },
  {
    id: "vercel",
    name: "Vercel",
    icon: SiVercel,
    href: "https://vercel.com/",
    category: "cloud",
    keywords: ["hosting", "deploy", "next", "serverless"],
    color: "#FFFFFF",
  },
  {
    id: "springboot",
    name: "Springboot",
    icon: SiSpringboot,
    href: "https://spring.io/projects/spring-boot",
    category: "backend",
    keywords: [
      "java",
      "open-source",
      "framework",
      "spring ecosystem",
      "convention over configuration",
      "opinionated defaults",
      "standalone applications",
      "microservices",
      "web applications",
      "production-grade",
      "auto-configuration",
      "embedded server",
      "tomcat",
      "jetty",
      "undertow",
      "rest apis",
      "maven",
      "gradle",
      "dependency injection",
      "inversion of control",
      "spring initializr",
      "actuator",
      "monitoring",
      "metrics",
      "health checks",
      "externalized configuration",
      "profiles",
      "spring data",
      "jpa",
      "security",
      "authentication",
      "authorization",
    ],

    color: "#6DB33F",
  },
  {
    id: "sql-developer",
    name: "SQL Developer",
    icon: SiOracle,
    href: "https://www.oracle.com/database/sqldeveloper/",
    category: "tools",
    keywords: [
      "oracle",
      "database",
      "sql",
      "plsql",
      "pl/sql",
      "ide",
      "query",
      "schema",
      "data modeling",
      "database administration",
      "dba",
      "stored procedures",
      "triggers",
      "packages",
      "functions",
      "views",
      "indexes",
      "sequences",
      "tables",
      "relational",
      "rdbms",
      "data migration",
      "sql tuning",
      "explain plan",
      "performance",
      "debugging",
      "version control",
      "reports",
      "data export",
      "data import",
      "connections",
      "worksheets",
    ],
    color: "#F80000",
  },
];
